"""Book Part I, the dictionary: what each packet key means IN THIS SYSTEM.

Hand-written from reading the code that computes each key (code_ref names it). The numeric bands
of every scored metric are NOT written here: dictionary.py generates them by probing the scorer
itself, so they cannot drift from the code. Fleet values (weights, floors) are read from the fleet
settings at generation time.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, replace

# scale vocabulary
SUB = "sub_score_0_100"
UNIT = "fraction_0_1"
PCT = "percent"
PP = "percentage_points"
RATIO = "ratio"
RAW = "raw_indicator"
COUNT = "count"
USD = "usd"
FLAG = "flag_0_1"
DAYS = "days"

# direction vocabulary (for a long buy)
HIGHER = "higher_better"
LOWER = "lower_better"
CONTRA = "contrarian_low_is_bullish"
NONE = "not_directional"


@dataclass(frozen=True)
class Entry:
    key: str
    pillar: str
    scale: str
    direction: str
    what: str
    code_ref: str
    pitfall: str = ""
    probe: str = ""  # name of a scorer probe in dictionary.py; its bands are generated
    alt_scales: tuple[str, ...] = ()  # the same key rendered in another unit elsewhere in the packet
    pattern: str = ""  # regex for keys that embed a name or period, e.g. holding_<TICKER>_value_usd
    # Who must read it (DL-264 amendment 8): "evidence" = every seat (the default, so a new number is
    # read by everyone until someone decides otherwise); "bookkeeping" = the judge must, debaters may.
    tier: str = "evidence"
    # "proven" = a deterministic computation or a model with demonstrated skill; "unproven" = a model
    # output whose skill is not yet shown live. Unproven numbers are presented and read, but may not
    # carry a decision on their own (DEC-FORM-08).
    status: str = "proven"


E = Entry
ENTRIES: tuple[Entry, ...] = (
    # ---- analyst: composite and pillars --------------------------------------------------
    E(
        "confidence_score",
        "composite",
        UNIT,
        HIGHER,
        "The analyst's confidence = confidence_floor + confidence_span x composite_score. Gated against the "
        "regime's base_min_confidence_score.",
        "agents/analyst/domain/scoring.py:score_candidate",
        "Not a probability of profit. It is a linear rescale of the composite score.",
    ),
    E(
        "confidence",
        "composite",
        UNIT,
        HIGHER,
        "Same number as confidence_score, repeated inside quant_metrics.",
        "agents/analyst/domain/scoring.py",
    ),
    E(
        "composite_score",
        "composite",
        UNIT,
        HIGHER,
        "Weighted mean of the pillars present: technical, fundamental, sentiment (weights in the house rules), "
        "renormalised over the pillars that exist.",
        "agents/analyst/domain/scoring.py:_composite",
        "A missing pillar is dropped, not scored as zero: the composite can rest on technicals alone.",
    ),
    E(
        "technical_score",
        "technical",
        UNIT,
        HIGHER,
        "Mean of all indicator sub-scores (/100), then blended 80/20 with the relative-strength score.",
        "agents/analyst/domain/technical_rules.py:score_technical; scoring.py:_apply_relative_strength",
        "It AVERAGES contrarian sub-scores (RSI, Bollinger, stochastic, Williams, RSI-2, NW deviation) with "
        "trend sub-scores (SMA-200, EMA, MACD, golden cross, OBV). An extended leader and a falling knife can "
        "score within a few points of each other. Read the sub-scores, never this number alone.",
    ),
    E(
        "fundamental_score",
        "fundamental",
        UNIT,
        HIGHER,
        "Mean of the fundamental sub-scores (pe, pb, roe, net_margin, current_ratio, debt_equity, eps_growth, "
        "revenue_growth) /100.",
        "agents/analyst/domain/fundamental_rules.py:score_fundamental",
    ),
    E(
        "analyst_sentiment_score",
        "sentiment",
        UNIT,
        HIGHER,
        "The analyst's news-headline sentiment pillar (0 all negative, 0.5 balanced, 1 all positive); 'n/a' "
        "when no headline contains a lexicon word.",
        "agents/analyst/domain/sentiment_rules.py:score_sentiment",
        "'n/a' means no signal, not neutral, and the composite then rests on the other pillars.",
    ),
    E(
        "sentiment_score",
        "sentiment",
        UNIT,
        HIGHER,
        "Same lexicon pillar as analyst_sentiment_score, inside quant_metrics. Each headline scores "
        "50+50*(pos-neg)/(pos+neg); headlines with no lexicon word are skipped.",
        "agents/analyst/domain/sentiment_rules.py:score_sentiment",
        "One strongly negative headline among few can pull the pillar to 0.",
    ),
    E(
        "sentiment_articles",
        "sentiment",
        COUNT,
        NONE,
        "Number of HEADLINES that contained at least one lexicon word.",
        "sentiment_rules.py",
        "Headlines, not articles read in full.",
    ),
    E(
        "sentiment_batch_weighted_articles",
        "sentiment",
        COUNT,
        NONE,
        "Weighted headline denominator used by the mean (a headline shared across tickers weighs less).",
        "sentiment_rules.py",
    ),
    E(
        "sentiment_positive_words",
        "sentiment",
        COUNT,
        NONE,
        "Lexicon WORD occurrences counted as positive.",
        "sentiment_rules.py",
        "Word counts, not article counts; they routinely exceed sentiment_articles (DL-112).",
    ),
    E(
        "sentiment_negative_words",
        "sentiment",
        COUNT,
        NONE,
        "Lexicon WORD occurrences counted as negative.",
        "sentiment_rules.py",
        "Word counts, not article counts (DL-112).",
    ),
    E(
        "provider_sentiment_score",
        "sentiment",
        "provider_scale_undeclared",
        HIGHER,
        "The data provider's own sentiment number for the ticker (scale not declared in our code). It does not "
        "feed the analyst's composite.",
        "agents/deliberator/context_market.py:market_lines",
        "A different scale and source from analyst_sentiment_score; do not compare the two numerically.",
    ),
    # ---- analyst: technical indicators (raw value + its sub-score) ------------------------
    E(
        "rsi",
        "technical",
        RAW,
        CONTRA,
        "14-period Relative Strength Index, 0-100.",
        "indicators.py:rsi",
        "Scored contrarian: high RSI (overbought) gets a LOW sub-score.",
        probe="rsi",
    ),
    E(
        "rsi_score",
        "technical",
        SUB,
        HIGHER,
        "Sub-score of rsi.",
        "technical_rules.py:score_rsi",
        "rsi_score=25 means rsi >= 70 (overbought), not weak momentum.",
        probe="rsi",
    ),
    E(
        "rsi2",
        "technical",
        RAW,
        CONTRA,
        "2-period RSI, 0-100: a very short-term overbought/oversold gauge.",
        "technical_rules_event.py",
        probe="rsi2",
    ),
    E(
        "rsi2_score",
        "technical",
        SUB,
        HIGHER,
        "Sub-score of rsi2 (contrarian).",
        "technical_rules_event.py:score_rsi2",
        probe="rsi2",
    ),
    E(
        "bollinger_position",
        "technical",
        "position_0_1",
        CONTRA,
        "Where the close sits inside the Bollinger band: 0 = lower band, 1 = upper band.",
        "technical_rules.py:score_bollinger",
        "Near the lower band is scored bullish (contrarian).",
        probe="bollinger",
    ),
    E(
        "bollinger_position_score",
        "technical",
        SUB,
        HIGHER,
        "Sub-score of bollinger_position.",
        "technical_rules.py:score_bollinger",
        probe="bollinger",
    ),
    E(
        "sma_distance_pct",
        "technical",
        PCT,
        HIGHER,
        "Close's distance above (+) or below (-) its 200-day SMA, in %.",
        "technical_rules.py:score_sma_distance",
        "Trend-following: below the SMA-200 scores low.",
        probe="sma",
    ),
    E(
        "sma_distance_pct_score",
        "technical",
        SUB,
        HIGHER,
        "Sub-score of sma_distance_pct.",
        "technical_rules.py:score_sma_distance",
        probe="sma",
    ),
    E(
        "ema_spread_pct",
        "technical",
        PCT,
        HIGHER,
        "Short EMA minus long EMA as % of price (positive = up-trend).",
        "technical_rules.py:score_ema_crossover",
        probe="ema",
    ),
    E(
        "ema_spread_pct_score",
        "technical",
        SUB,
        HIGHER,
        "Sub-score of ema_spread_pct.",
        "technical_rules.py:score_ema_crossover",
        probe="ema",
    ),
    E(
        "macd_histogram",
        "technical",
        RAW,
        HIGHER,
        "MACD line minus signal line, in price units.",
        "technical_rules.py:score_macd",
        "Its sub-score also depends on the sign of the MACD line, which the packet does not show.",
        probe="macd",
    ),
    E(
        "macd_histogram_score",
        "technical",
        SUB,
        HIGHER,
        "Sub-score from MACD line and histogram signs.",
        "technical_rules.py:score_macd",
        probe="macd",
    ),
    E(
        "golden_cross",
        "technical",
        FLAG,
        HIGHER,
        "1 when the 50-day SMA is above the 200-day SMA, else 0.",
        "technical_rules_event.py:score_golden_cross",
        probe="golden",
    ),
    E(
        "golden_cross_score",
        "technical",
        SUB,
        HIGHER,
        "Sub-score of golden_cross.",
        "technical_rules_event.py",
        probe="golden",
    ),
    E(
        "obv",
        "technical",
        RAW,
        NONE,
        "On-balance volume level (cumulative signed volume).",
        "technical_rules_event.py:score_obv",
        "The level itself means nothing; only OBV vs its signal line is scored.",
        probe="obv",
    ),
    E(
        "obv_score",
        "technical",
        SUB,
        HIGHER,
        "70 when OBV is above its signal average (accumulation), else 35.",
        "technical_rules_event.py:score_obv",
        probe="obv",
    ),
    E(
        "atr_pct",
        "technical",
        PCT,
        LOWER,
        "Average True Range as % of price: daily volatility.",
        "technical_rules_range.py:score_atr",
        "Lower volatility scores higher. It also sizes the scaled stop.",
        probe="atr",
    ),
    E(
        "atr_pct_score",
        "technical",
        SUB,
        HIGHER,
        "Sub-score of atr_pct.",
        "technical_rules_range.py:score_atr",
        probe="atr",
    ),
    E(
        "stochastic_k",
        "technical",
        RAW,
        CONTRA,
        "Stochastic %K, 0-100: close within the recent high-low range.",
        "technical_rules_range.py:score_stochastic",
        "Scored with %D (not shown): oversold high, overbought low.",
        probe="stochastic",
    ),
    E(
        "stochastic_k_score",
        "technical",
        SUB,
        HIGHER,
        "Sub-score from %K and %D.",
        "technical_rules_range.py:score_stochastic",
        probe="stochastic",
    ),
    E(
        "williams_r",
        "technical",
        RAW,
        CONTRA,
        "Williams %R, -100..0 (-100 = at the period low).",
        "technical_rules_range.py:score_williams",
        probe="williams",
    ),
    E(
        "williams_r_score",
        "technical",
        SUB,
        HIGHER,
        "Sub-score of williams_r (contrarian).",
        "technical_rules_range.py:score_williams",
        probe="williams",
    ),
    E(
        "choppiness",
        "technical",
        RAW,
        LOWER,
        "Choppiness index 0-100: low = trending, high = range-bound.",
        "technical_rules_range.py:score_choppiness",
        probe="chop",
    ),
    E(
        "choppiness_score",
        "technical",
        SUB,
        HIGHER,
        "Sub-score of choppiness.",
        "technical_rules_range.py:score_choppiness",
        probe="chop",
    ),
    E(
        "nw_deviation_pct",
        "technical",
        PCT,
        CONTRA,
        "Close's % deviation from a Nadaraya-Watson kernel-smoothed price line.",
        "technical_rules_pattern.py:score_kernel",
        "Below the smoothed line is scored bullish (contrarian).",
        probe="nw",
    ),
    E(
        "nw_deviation_pct_score",
        "technical",
        SUB,
        HIGHER,
        "Sub-score of nw_deviation_pct.",
        "technical_rules_pattern.py:score_kernel",
        probe="nw",
    ),
    E(
        "turnaround",
        "technical",
        FLAG,
        HIGHER,
        "1 when the turnaround pattern detector fires, else 0.",
        "technical_rules_pattern.py:score_turnaround",
        probe="turnaround",
    ),
    E(
        "turnaround_score",
        "technical",
        SUB,
        HIGHER,
        "75 when turnaround fires, else neutral 50.",
        "technical_rules_pattern.py",
        probe="turnaround",
    ),
    E(
        "indicators_available",
        "technical",
        COUNT,
        NONE,
        "How many indicator sub-scores were averaged.",
        "technical_rules.py:score_technical",
        "Fewer indicators = a noisier technical_score.",
    ),
    E(
        "history_bars",
        "technical",
        COUNT,
        HIGHER,
        "Daily bars the analyst had for this ticker.",
        "scoring.py",
        "Below 200 the SMA-200 and golden cross cannot compute and are absent.",
    ),
    E(
        "relative_strength",
        "relative_strength",
        PP,
        HIGHER,
        "ANALYST: the stock's trailing return minus the benchmark's (SPY) over the same window, in percentage points.",
        "agents/analyst/domain/relative_strength.py:compute_relative_strength",
        "The SCANNER's relative_strength is a different metric with the same name: the stock's own total return "
        "as a fraction (0.12 = +12 %), with no benchmark. Check which block the value is in.",
        probe="rs",
    ),
    E(
        "rs_score",
        "relative_strength",
        SUB,
        HIGHER,
        "Sub-score of the analyst relative_strength; blended 20 % into technical_score.",
        "relative_strength.py:score_relative_strength",
        probe="rs",
    ),
    # ---- analyst: fundamental sub-scores (NOT the raw ratios) -----------------------------
    E(
        "pe",
        "fundamental",
        SUB,
        HIGHER,
        "SUB-SCORE of the trailing P/E ratio (cheaper scores higher).",
        "fundamental_rules.py:_FUNDAMENTAL_RULES",
        "NOT the P/E ratio. The ratio is peBasicExclExtraTTM in the "
        "Fundamentals line. A loss-maker has no pe key at all.",
        probe="fund:pe",
    ),
    E(
        "pb",
        "fundamental",
        SUB,
        HIGHER,
        "SUB-SCORE of price/book (cheaper scores higher).",
        "fundamental_rules.py",
        "NOT the ratio; raw value is pbQuarterly.",
        probe="fund:pb",
    ),
    E(
        "roe",
        "fundamental",
        SUB,
        HIGHER,
        "SUB-SCORE of return on equity.",
        "fundamental_rules.py",
        "NOT the ratio; raw value is roeTTM (in %).",
        probe="fund:roe",
    ),
    E(
        "net_margin",
        "fundamental",
        SUB,
        HIGHER,
        "SUB-SCORE of net profit margin.",
        "fundamental_rules.py",
        "Raw value is netProfitMarginTTM (in %).",
        probe="fund:net_margin",
    ),
    E(
        "current_ratio",
        "fundamental",
        SUB,
        HIGHER,
        "SUB-SCORE of the current ratio (liquidity).",
        "fundamental_rules.py",
        "Raw value is currentRatioQuarterly.",
        probe="fund:current_ratio",
    ),
    E(
        "debt_equity",
        "fundamental",
        SUB,
        HIGHER,
        "SUB-SCORE of debt/equity (less debt scores higher).",
        "fundamental_rules.py",
        "A HIGH debt_equity sub-score means LOW leverage.",
        probe="fund:debt_equity",
    ),
    E(
        "eps_growth",
        "fundamental",
        SUB,
        HIGHER,
        "SUB-SCORE of trailing EPS growth year on year.",
        "fundamental_rules.py",
        "Raw value is epsGrowthTTMYoy (in %).",
        probe="fund:eps_growth",
    ),
    E(
        "revenue_growth",
        "fundamental",
        SUB,
        HIGHER,
        "SUB-SCORE of trailing revenue growth year on year.",
        "fundamental_rules.py",
        "Raw value is revenueGrowthTTMYoy (in %).",
        probe="fund:revenue_growth",
    ),
    E(
        "fundamentals_available",
        "fundamental",
        COUNT,
        NONE,
        "How many fundamental sub-scores were averaged.",
        "fundamental_rules.py:score_fundamental",
    ),
    # vendor raw fundamentals (Fundamentals line)
    E(
        "peBasicExclExtraTTM",
        "fundamental",
        RATIO,
        LOWER,
        "The actual trailing P/E ratio (vendor field).",
        "Finnhub metric; scored into pe",
    ),
    E("pbQuarterly", "fundamental", RATIO, LOWER, "Price/book ratio (vendor).", "Finnhub; scored into pb"),
    E("roeTTM", "fundamental", PCT, HIGHER, "Return on equity, % (vendor).", "Finnhub; scored into roe"),
    E(
        "netProfitMarginTTM",
        "fundamental",
        PCT,
        HIGHER,
        "Net profit margin, % (vendor).",
        "Finnhub; scored into net_margin",
    ),
    E(
        "currentRatioQuarterly",
        "fundamental",
        RATIO,
        HIGHER,
        "Current assets / current liabilities (vendor).",
        "Finnhub; scored into current_ratio",
    ),
    E(
        "totalDebt/totalEquityQuarterly",
        "fundamental",
        RATIO,
        LOWER,
        "Debt/equity ratio (vendor).",
        "Finnhub; scored into debt_equity",
    ),
    E(
        "epsGrowthTTMYoy",
        "fundamental",
        PCT,
        HIGHER,
        "EPS growth year on year, % (vendor).",
        "Finnhub; scored into eps_growth",
    ),
    E(
        "revenueGrowthTTMYoy",
        "fundamental",
        PCT,
        HIGHER,
        "Revenue growth year on year, % (vendor).",
        "Finnhub; scored into revenue_growth",
    ),
    # ---- stop / target -------------------------------------------------------------------
    E(
        "suggested_stop_pct",
        "risk",
        PCT,
        NONE,
        "Analyst's protective stop distance below entry.",
        "agents/analyst/domain/stop_target.py",
        "In scaled mode it is a multiple of atr_pct.",
    ),
    E(
        "suggested_target_pct",
        "risk",
        PCT,
        NONE,
        "Analyst's profit target above entry.",
        "stop_target.py",
        "In scaled mode it is the trailing median 10-session favorable excursion (favorable_excursion_pct), "
        "which can be SMALLER than the stop.",
    ),
    E(
        "applied_stop_pct",
        "risk",
        PCT,
        NONE,
        "Stop actually applied (fleet mode = scaled).",
        "stop_target.py",
    ),
    E("applied_target_pct", "risk", PCT, NONE, "Target actually applied.", "stop_target.py"),
    E(
        "favorable_excursion_pct",
        "risk",
        "fraction",
        HIGHER,
        "Median best gain reached within favorable_excursion_horizon_days over the trailing windows (0.0266 = 2.66 %).",
        "target_excursion_metrics.py",
        "A fraction here, while the stop/target lines show percent.",
    ),
    E(
        "favorable_excursion_horizon_days",
        "risk",
        DAYS,
        NONE,
        "Horizon (sessions) of the excursion measure.",
        "target_excursion_metrics.py",
    ),
    E(
        "favorable_excursion_lookback_windows",
        "risk",
        COUNT,
        NONE,
        "Trailing windows sampled.",
        "target_excursion_metrics.py",
    ),
    E(
        "favorable_excursion_sample_count",
        "risk",
        COUNT,
        NONE,
        "Windows actually measured.",
        "target_excursion_metrics.py",
    ),
    E(
        "value_reward_risk_ratio",
        "risk",
        RATIO,
        HIGHER,
        "target_pct / stop_pct for this order.",
        "agents/portfolio_manager/domain/gate_report.py",
        "The gate is DISCLOSURE_ONLY at threshold 0 on the fleet: a ratio below 1 still PASSES.",
    ),
    E(
        "applied_reward_risk_ratio",
        "risk",
        RATIO,
        HIGHER,
        "Reward/risk at the applied stop and target.",
        "stop_target",
    ),
    # ---- scanner -------------------------------------------------------------------------
    E(
        "scanner_score",
        "scanner",
        RAW,
        HIGHER,
        "The scanner's ranking score (equals its relative_strength feature).",
        "agents/scanner/domain/ranking.py",
    ),
    E(
        "rank_ordinal",
        "scanner",
        COUNT,
        LOWER,
        "Rank among scanner candidates (1 = strongest).",
        "ranking.py",
    ),
    E(
        "average_volume",
        "scanner",
        "shares",
        HIGHER,
        "Mean daily volume over the scanner window.",
        "scanner filters.py",
    ),
    E(
        "beta",
        "scanner",
        RATIO,
        NONE,
        "Beta vs the benchmark; >1 moves more than the market.",
        "scanner filters.py",
        "Filtered at max_beta; matters more in risk-off regimes.",
    ),
    E(
        "days_to_earnings",
        "scanner",
        DAYS,
        HIGHER,
        "Calendar days to the next earnings report.",
        "scanner filters.py:_days_to_earnings",
        "Names inside the earnings exclusion are already dropped; a value "
        "just above it means the report lands inside a 10-session hold.",
    ),
    E("latest_close", "scanner", USD, NONE, "Latest close used by the scanner.", "scanner filters.py"),
    # ---- regime --------------------------------------------------------------------------
    E(
        "label",
        "regime",
        "enum",
        NONE,
        "Market regime label from the VIX (risk_on/neutral/risk_off/high/extreme).",
        "agents/provider/domain/regime.py:classify_regime",
    ),
    E(
        "vix_index",
        "regime",
        "index_points",
        LOWER,
        "CBOE VIX level the regime was classified on.",
        "provider regime",
    ),
    E(
        "base_min_confidence_score",
        "regime",
        UNIT,
        NONE,
        "Regime floor the analyst's confidence must clear.",
        "provider settings",
    ),
    E(
        "base_stop_loss_pct",
        "regime",
        PCT,
        NONE,
        "Regime default stop (used when no analyst stop).",
        "provider settings",
    ),
    E("base_take_profit_pct", "regime", PCT, NONE, "Regime default target.", "provider settings"),
    E(
        "base_max_holding_days",
        "regime",
        DAYS,
        NONE,
        "Regime's intended maximum holding period, in sessions.",
        "provider settings",
        "Nothing in the fleet sells on this horizon today (work-queue 92).",
    ),
    # ---- PM gates (value_* / threshold_* pairs) ------------------------------------------
    E(
        "value_portfolio_ratio",
        "pm_gate",
        RATIO,
        LOWER,
        "sizing: position value / portfolio value.",
        "agents/portfolio_manager/domain/sizing.py",
        "Fleet cap is 1 % of the portfolio per name.",
    ),
    E(
        "value_cluster_exposure_ratio",
        "pm_gate",
        RATIO,
        LOWER,
        "correlated_cluster_pct: share of deployed capital in names correlated with this one.",
        "portfolio_manager/domain/correlation.py",
        "NOT-EVALUATED while deployment is below its floor: the gate did not look, it did not pass.",
    ),
    E(
        "value_sector_exposure_ratio",
        "pm_gate",
        RATIO,
        LOWER,
        "max_sector_pct: sector share of deployed capital.",
        "portfolio_manager/domain/concentration.py",
        "NOT-EVALUATED below the deployment floor.",
    ),
    E(
        "value_sector_issuers",
        "pm_gate",
        COUNT,
        LOWER,
        "max_names_per_sector: issuers in the sector incl. this one.",
        "portfolio_manager/domain/concentration.py",
    ),
    E(
        "value_positions",
        "pm_gate",
        COUNT,
        LOWER,
        "max_positions: open issuers incl. this one.",
        "position_gates.py",
    ),
    E(
        "value_order_cost_usd",
        "pm_gate",
        USD,
        NONE,
        "cash_available: this order's cost.",
        "position_gates.py",
    ),
    E(
        "value_shares",
        "pm_gate",
        COUNT,
        NONE,
        "min_order_quantity: whole shares ordered.",
        "position_gates.py",
    ),
)


# ---- every other number in the packet (operator, 2026-10-03: ALL quant numbers are interpreted) --------
MORE: tuple[Entry, ...] = (
    # order and prices
    E(
        "quantity_shares",
        "order",
        COUNT,
        NONE,
        "Shares the PM approved for this order.",
        "agents/portfolio_manager/domain/sizing.py",
    ),
    E(
        "est_price_usd",
        "order",
        USD,
        NONE,
        "Price the PM sized the order at (latest close).",
        "portfolio_manager run.py:latest_close_prices",
    ),
    E(
        "stop_pct",
        "order",
        PCT,
        NONE,
        "The order's protective stop distance below entry.",
        "PM gate_report.py",
        "Rendered as PERCENT in the 'PM order' line (4.64%) and as a FRACTION in the reward_risk detail (0.0464).",
        alt_scales=("fraction",),
    ),
    E(
        "target_pct",
        "order",
        PCT,
        NONE,
        "The order's profit target above entry.",
        "PM gate_report.py",
        "PERCENT in the 'PM order' line, FRACTION in the reward_risk detail.",
        alt_scales=("fraction",),
    ),
    E("open_usd", "market_data", USD, NONE, "Latest daily bar: open.", "provider MarketData.bars"),
    E("high_usd", "market_data", USD, NONE, "Latest daily bar: high.", "provider MarketData.bars"),
    E("low_usd", "market_data", USD, NONE, "Latest daily bar: low.", "provider MarketData.bars"),
    E("close_usd", "market_data", USD, NONE, "Latest daily bar: close.", "provider MarketData.bars"),
    E(
        "volume_shares",
        "market_data",
        "shares",
        HIGHER,
        "Latest daily bar: volume.",
        "provider MarketData.bars",
    ),
    # data-quality and scanner counts
    E(
        "requested_tickers",
        "data_quality",
        COUNT,
        NONE,
        "Tickers the provider was asked for in this run.",
        "provider DataQualityTrace",
    ),
    E(
        "returned_tickers",
        "data_quality",
        COUNT,
        HIGHER,
        "Tickers it returned; below requested means missing data.",
        "provider DataQualityTrace",
    ),
    E(
        "universe_tickers",
        "scanner",
        COUNT,
        NONE,
        "Size of the scanner's universe this run.",
        "scanner FilterTrace",
    ),
    E("evaluated_tickers", "scanner", COUNT, NONE, "Tickers the scanner evaluated.", "scanner FilterTrace"),
    # stop/target variants
    E(
        "flat_stop_pct",
        "risk",
        PCT,
        NONE,
        "Stop under the flat mode (the regime base stop).",
        "analyst stop_target.py",
    ),
    E("flat_target_pct", "risk", PCT, NONE, "Target under the flat mode.", "analyst stop_target.py"),
    E(
        "scaled_stop_pct",
        "risk",
        PCT,
        NONE,
        "Stop under the scaled mode: 2 x atr_pct on the fleet.",
        "analyst stop_target.py",
        "The fleet runs scaled, so this is the applied stop.",
    ),
    E(
        "scaled_target_pct",
        "risk",
        PCT,
        NONE,
        "Target under the scaled mode: the trailing favorable excursion.",
        "analyst stop_target.py",
    ),
    E(
        "flat_reward_risk_ratio",
        "risk",
        RATIO,
        HIGHER,
        "target/stop under the flat mode.",
        "PM reward_risk_detail.py",
    ),
    E(
        "scaled_reward_risk_ratio",
        "risk",
        RATIO,
        HIGHER,
        "target/stop under the scaled mode.",
        "PM reward_risk_detail.py",
        "Below 1 means the target is closer than the stop.",
    ),
    E(
        "decision_atr_pct",
        "risk",
        PCT,
        LOWER,
        "ATR % the analyst had at decision time, carried on the order.",
        "contracts/portfolio_manager.py:OrderIntent",
    ),
    # PM gate bookkeeping
    E(
        "portfolio_value_usd",
        "pm_gate",
        USD,
        NONE,
        "The account EQUITY the PM sizes against (cash + holdings).",
        "agents/portfolio_manager/graph_portfolio.py",
        "Equity, not cash: the PM's `cash` field carries equity in production.",
    ),
    E(
        "deployed_portfolio_usd",
        "pm_gate",
        USD,
        NONE,
        "Market value of current holdings: the denominator of the sector and cluster gates.",
        "PM concentration.py / correlation.py",
        "Concentration is measured against DEPLOYED capital, not equity.",
    ),
    E("position_value_usd", "pm_gate", USD, NONE, "This order's value (sizing gate).", "PM sizing.py"),
    E(
        "existing_issuer_value_usd",
        "pm_gate",
        USD,
        LOWER,
        "Value already held in this issuer.",
        "PM sizing.py",
    ),
    E(
        "existing_sector_issuers",
        "pm_gate",
        COUNT,
        LOWER,
        "Issuers already held in this sector.",
        "PM concentration.py",
    ),
    E(
        "held_sector_value_usd",
        "pm_gate",
        USD,
        LOWER,
        "Value already held in this sector.",
        "PM sector_gate_outcomes.py",
    ),
    E(
        "deployed_this_batch_usd",
        "pm_gate",
        USD,
        NONE,
        "Cost of other orders approved earlier in this batch, in this sector.",
        "PM sector_book.py",
    ),
    E(
        "order_cost_usd",
        "pm_gate",
        USD,
        NONE,
        "This order's cost (sector gate).",
        "PM sector_gate_outcomes.py",
    ),
    E(
        "cash_buffer_pct",
        "pm_gate",
        "fraction",
        NONE,
        "Share of equity the PM keeps as cash (0.05 = 5 %).",
        "PM settings cash_buffer_pct",
    ),
    E(
        "reserved_cash_this_batch_usd",
        "pm_gate",
        USD,
        NONE,
        "Cash already reserved by earlier orders this batch.",
        "PM position_gates.py",
    ),
    E("deployment_pct", "pm_gate", "fraction", NONE, "Deployed capital / equity.", "PM deployment_floor.py"),
    E(
        "deployment_floor_pct",
        "pm_gate",
        "fraction",
        NONE,
        "Below this deployment the concentration gates do not evaluate.",
        "PM deployment_floor.py",
        "NOT-EVALUATED below the floor means the gate did not look.",
    ),
    E(
        "cluster_value_usd",
        "pm_gate",
        USD,
        LOWER,
        "Order cost + this issuer's holding + each correlated holding x its ramp weight.",
        "PM correlation.py",
    ),
    E(
        "cluster_weight_total",
        "pm_gate",
        "weight_sum",
        LOWER,
        "Sum of the ramp weights of held issuers correlated with this one.",
        "PM correlation_census.py",
    ),
    E(
        "examined_issuers",
        "pm_gate",
        COUNT,
        NONE,
        "Held issuers the correlation gate compared with this one.",
        "PM correlation_census.py",
    ),
    E(
        "correlated_issuers",
        "pm_gate",
        "compound",
        LOWER,
        "Each held issuer above the ramp start, as TICKER:correlation:wWEIGHT "
        "(daily-return correlation over the lookback; weight from the ramp).",
        "PM correlation_census.py",
        "A correlation of 0.70 counts about half of that holding toward the cluster.",
    ),
    E(
        "below_threshold_top",
        "pm_gate",
        "compound",
        NONE,
        "The highest correlations that stayed below the ramp start, TICKER:correlation.",
        "PM correlation_census.py",
    ),
    E(
        "correlation_ramp",
        "pm_gate",
        "compound",
        NONE,
        "Correlations at or below the first number count 0, at or above the second "
        "count fully, linear in between.",
        "PM correlation_ramp.py:contribution",
    ),
    E(
        "min_pair_overlap_bars",
        "pm_gate",
        COUNT,
        HIGHER,
        "Fewest overlapping bars in any compared pair.",
        "PM correlation_census.py",
    ),
    E(
        "skipped_pairs",
        "pm_gate",
        COUNT,
        LOWER,
        "Pairs skipped for too little overlapping history.",
        "PM correlation_census.py",
    ),
    E(
        "threshold_portfolio_ratio",
        "pm_gate",
        RATIO,
        NONE,
        "sizing cap: max position value / equity (fleet: 0.01).",
        "PM settings max_position_pct",
    ),
    E("threshold_shares", "pm_gate", COUNT, NONE, "min_order_quantity threshold.", "PM settings"),
    E("threshold_positions", "pm_gate", COUNT, NONE, "max_positions threshold (fleet: 60).", "PM settings"),
    E(
        "threshold_available_cash_usd",
        "pm_gate",
        USD,
        NONE,
        "Cash available for this order after buffer and reservations.",
        "PM position_gates.py",
        "Rendered in scientific notation (7.441e+04 = 74,410).",
    ),
    E(
        "threshold_reward_risk_ratio",
        "pm_gate",
        RATIO,
        NONE,
        "reward_risk threshold (fleet: 0, disclosure only).",
        "PM settings",
    ),
    E(
        "threshold_sector_exposure_ratio",
        "pm_gate",
        RATIO,
        NONE,
        "max_sector_pct threshold (share of deployed capital).",
        "PM settings",
    ),
    E("threshold_sector_issuers", "pm_gate", COUNT, NONE, "max_names_per_sector threshold.", "PM settings"),
    E(
        "threshold_cluster_exposure_ratio",
        "pm_gate",
        RATIO,
        NONE,
        "max_correlated_cluster_pct threshold (share of deployed capital).",
        "PM settings",
    ),
    # lab supplement: computed by the fleet's code, not shown in production
    E(
        "macd_line_price",
        "supplement",
        RAW,
        HIGHER,
        "MACD line (fast EMA - slow EMA), price units.",
        "analyst indicators.py:macd",
        "Its sign decides macd_histogram_score together with the histogram.",
    ),
    E(
        "macd_signal_price",
        "supplement",
        RAW,
        NONE,
        "MACD signal line; histogram = line - signal.",
        "analyst indicators.py:macd",
    ),
    E(
        "stochastic_d",
        "supplement",
        RAW,
        CONTRA,
        "Stochastic %D (smoothed %K); scored together with %K.",
        "analyst indicators_range.py:stochastic",
    ),
    E(
        "obv_signal",
        "supplement",
        RAW,
        NONE,
        "OBV signal line; OBV above it scores 70, below 35.",
        "analyst indicators_event.py:obv",
    ),
    E(
        "sma_N_usd",
        "supplement",
        USD,
        NONE,
        "Simple moving average over the N days in the key (sma_50_usd, sma_200_usd).",
        "analyst indicators.py",
        "sma_50 above sma_200 is the golden cross; close vs sma_200 is sma_distance_pct.",
        pattern=r"sma_\d+_usd",
    ),
    E(
        "ema_N_usd",
        "supplement",
        USD,
        NONE,
        "Exponential moving average over the N days in the key (short and long).",
        "analyst indicators.py",
        "ema_spread_pct is the short-minus-long gap as % of price.",
        pattern=r"ema_\d+_usd",
    ),
    E(
        "bollinger_middle_usd",
        "supplement",
        USD,
        NONE,
        "Bollinger middle band (window SMA).",
        "analyst indicators.py:bollinger_position",
    ),
    E(
        "bollinger_upper_usd",
        "supplement",
        USD,
        NONE,
        "Bollinger upper band (middle + sigma x std).",
        "analyst indicators.py",
    ),
    E(
        "bollinger_lower_usd",
        "supplement",
        USD,
        NONE,
        "Bollinger lower band (middle - sigma x std).",
        "analyst indicators.py",
    ),
    E("account_cash_usd", "supplement", USD, NONE, "Broker cash.", "graph_portfolio.py account_cash_cents"),
    E(
        "account_equity_usd",
        "supplement",
        USD,
        NONE,
        "Broker equity (cash + holdings).",
        "graph_portfolio.py account_equity_cents",
    ),
    E(
        "buying_power_usd",
        "supplement",
        USD,
        NONE,
        "Broker buying power.",
        "graph_portfolio.py account_buying_power_cents",
    ),
    E(
        "deployed_usd",
        "supplement",
        USD,
        NONE,
        "Market value of current holdings.",
        "graph_portfolio.py position_values",
    ),
    E("open_positions", "supplement", COUNT, NONE, "Number of current holdings.", "graph_portfolio.py"),
    E(
        "holding_TICKER_shares",
        "supplement",
        COUNT,
        NONE,
        "Shares held in that ticker.",
        "graph_portfolio.py",
        pattern=r"holding_[A-Z]+_shares",
    ),
    E(
        "holding_TICKER_value_usd",
        "supplement",
        USD,
        NONE,
        "Market value held in that ticker.",
        "graph_portfolio.py",
        pattern=r"holding_[A-Z]+_value_usd",
    ),
)
BARRIER: tuple[Entry, ...] = (
    E(
        "barrier_p_stop_first",
        "forecast",
        UNIT,
        LOWER,
        "Forecaster's probability that the stop is touched before the target within 10 sessions "
        "(GARCH(1,1)-t fitted on ~760 bars, 1,000 simulated paths).",
        "agents/forecaster/barrier_forecast.py",
        "UNPROVEN: no live skill shown yet. Read it, weigh it, never decide on it alone (DEC-FORM-08).",
        status="unproven",
    ),
    E(
        "barrier_p_target_first",
        "forecast",
        UNIT,
        HIGHER,
        "Probability the target is touched before the stop within 10 sessions.",
        "agents/forecaster/barrier_forecast.py",
        "UNPROVEN, as above.",
        status="unproven",
    ),
    E(
        "barrier_p_neither",
        "forecast",
        UNIT,
        NONE,
        "Probability neither is touched within 10 sessions.",
        "agents/forecaster/barrier_forecast.py",
        "UNPROVEN, as above.",
        status="unproven",
    ),
    E(
        "barrier_horizon_sessions",
        "forecast",
        DAYS,
        NONE,
        "Horizon of the barrier forecast, in sessions.",
        "forecaster barrier_garch.py HORIZON_SESSIONS",
    ),
    E(
        "barrier_history_bars",
        "forecast",
        COUNT,
        HIGHER,
        "Bars the GARCH model was fitted on.",
        "forecaster barrier_forecast.py",
    ),
    E(
        "barrier_settled_claims",
        "forecast",
        COUNT,
        HIGHER,
        "Past barrier forecasts already settled against "
        "what happened; the forecast's skill cannot be judged before enough have settled.",
        "forecaster barrier_skill.py",
    ),
)

# Numbers that describe the machinery rather than the stock or the market: the judge must read them,
# debaters may (DL-264 amendment 8).
BOOKKEEPING = {
    "requested_tickers",
    "returned_tickers",
    "universe_tickers",
    "evaluated_tickers",
    "rank_ordinal",
    "indicators_available",
    "fundamentals_available",
    "history_bars",
    "sentiment_articles",
    "sentiment_batch_weighted_articles",
    "sentiment_positive_words",
    "sentiment_negative_words",
    "favorable_excursion_horizon_days",
    "favorable_excursion_lookback_windows",
    "favorable_excursion_sample_count",
    "open_usd",
    "high_usd",
    "low_usd",
    "volume_shares",
    "latest_close",
    "est_price_usd",
    "quantity_shares",
    "position_value_usd",
    "order_cost_usd",
    "value_order_cost_usd",
    "value_shares",
    "value_positions",
    "cash_buffer_pct",
    "reserved_cash_this_batch_usd",
    "deployed_this_batch_usd",
    "examined_issuers",
    "min_pair_overlap_bars",
    "skipped_pairs",
    "correlation_ramp",
    "below_threshold_top",
    "threshold_portfolio_ratio",
    "threshold_shares",
    "threshold_positions",
    "threshold_available_cash_usd",
    "threshold_reward_risk_ratio",
    "threshold_sector_exposure_ratio",
    "threshold_sector_issuers",
    "threshold_cluster_exposure_ratio",
    "base_stop_loss_pct",
    "base_take_profit_pct",
    "base_max_holding_days",
    "account_cash_usd",
    "buying_power_usd",
    "open_positions",
    "holding_TICKER_shares",
    "barrier_horizon_sessions",
    "barrier_history_bars",
    "confidence",
}
ENTRIES = tuple(
    replace(e, tier="bookkeeping") if e.key in BOOKKEEPING else e for e in ENTRIES + MORE + BARRIER
)

_EXACT = {e.key: e for e in ENTRIES}
_PATTERNS = [(re.compile(f"^{e.pattern}$"), e) for e in ENTRIES if e.pattern]


def lookup(key: str) -> Entry | None:
    """The entry for a packet key, by exact name or by pattern (keys that embed a ticker or a period)."""
    if key in _EXACT:
        return _EXACT[key]
    return next((e for rx, e in _PATTERNS if rx.match(key)), None)
