"""Render sprint-status classifications for a reader.

Agent: tooling
Role: turn a StatusReport into the console listing and the refusal report.
External I/O: none — callers own stdout and the report file.

Split out of `check_sprint_status.py` at merge review: that module reached 227
lines against the repo's 200-line hard block. `make ci` did not object, because
the size check does not read `scripts/` — which is work-queue item **78**, and
adding a sixteenth oversized file there would have made the row worse. Reading
and deciding stay in the checker; only presentation lives here.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from scripts.sprint_status_types import DocumentStatus, StatusReport

_COUNTED_STATUSES = ("SPEC", "BUILT", "MERGED", "UNMAPPED", "MISSING")


def relative_path(report: StatusReport, entry: DocumentStatus) -> str:
    """Path of one document relative to the scanned root."""
    return entry.path.relative_to(report.root).as_posix()


def counts_line(report: StatusReport) -> str:
    """One line carrying every tally, including the refusals."""
    counts = " ".join(
        f"{status}={report.count(status)}" for status in _COUNTED_STATUSES
    )
    return f"docs_seen={len(report.entries)} {counts}"


def render_report(report: StatusReport) -> str:
    """Render classifications with each source line left intact beside its token."""
    lines = [
        f"{relative_path(report, entry)}: {entry.status} | "
        f"{entry.line or '<no **Status:** line>'}"
        for entry in report.entries
    ]
    lines.append(counts_line(report))
    return "\n".join(lines)


def render_unmapped_report(report: StatusReport) -> str:
    """Render the refusal list that a human must review before any migration."""
    lines = [
        "# Sprint Status Refusals",
        "",
        "Generated by `uv run python scripts/check_sprint_status.py --report`.",
        (
            "The checker never changes a sprint document; "
            "this report preserves each refusal."
        ),
        "",
        counts_line(report),
    ]
    for status in ("UNMAPPED", "MISSING"):
        lines.extend(["", f"## {status}", ""])
        for entry in report.entries:
            if entry.status == status:
                line = entry.line or "<no **Status:** line>"
                lines.append(f"- `{relative_path(report, entry)}`: {line}")
    return "\n".join(lines) + "\n"
